/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DAO.DAOFornecedor;
import Programa.Fornecedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas Calzavara
 */
public class InterfaceFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceFornecedor
     */
    public InterfaceFornecedor() {
        initComponents();
        setTitle("Fornecedores");
        consultarTodos();
    }
    
    private void consultarTodos(){
        ArrayList<Fornecedor> forns = new ArrayList<Fornecedor>();
          DAOFornecedor c = new DAOFornecedor();
          
        try {
            
            forns = (ArrayList<Fornecedor>) c.consultaTodos();
            
        } catch (SQLException ex) {
            Logger.getLogger(InterfaceCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        if( forns.isEmpty()){
            JOptionPane.showMessageDialog(null, "banco vazio");
            return;        
        }
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Razão Social", "CNPJ", "Nome Fantasia", "Inscrição Estadual", "Telefone", "Rua", "Bairro", "Numero", "Cidade", "UF", "Pedido Minimo","Observações"});
        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0; i < forns.size(); i++) {
            fila[0] = forns.get(i).getRazaosocial();
            fila[1] = forns.get(i).getCnpj();
            fila[2] = forns.get(i).getNomefantasia();
            fila[3] = forns.get(i).getInscricaoestadual();
            fila[4] = forns.get(i).getTelefone();
            fila[5] = forns.get(i).getRua();
            fila[6] = forns.get(i).getBairro();
            fila[7] = forns.get(i).getNumero();
            fila[8] = forns.get(i).getCidade();
            fila[9] = forns.get(i).getUf();
            fila[10] = forns.get(i).getPedidominimo();
            fila[11] = forns.get(i).getObservacoes();
            modelo.addRow(fila);
        }
        Tabela.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnpj = new javax.swing.JFormattedTextField();
        razao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("CNPJ:");

        jLabel2.setText("Razão Social:");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar Todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jButton3.setText("Incluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Fechar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1621, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(razao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(razao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DAOFornecedor f = new DAOFornecedor();
        if ("  .   .   /    -  ".equals(cnpj.getText()) && razao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Prencha o CNPJ ou Razão Social.");
        }
        else if(razao.getText().isEmpty()){
            Fornecedor forns = null;
            try {
                forns = f.consulta(cnpj.getText());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não encontrado", "Mensagem", JOptionPane.ERROR_MESSAGE, null);
                cnpj.setText(null);
                return;
            }
            if(forns.getCnpj() == null){
                JOptionPane.showMessageDialog(null, "Não encontrado", "Mensagem", JOptionPane.ERROR_MESSAGE, null);
                cnpj.setText(null);
                return;
            }

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Razão Social", "CNPJ", "Nome Fantasia", "Inscrição Estadual", "Telefone", "Rua", "Bairro", "Numero", "Cidade", "UF", "Pedido Minimo", "Observações"});
            Object[] fila = new Object[modelo.getColumnCount()];

            fila[0] = forns.getRazaosocial();
            fila[1] = forns.getCnpj();
            fila[2] = forns.getNomefantasia();
            fila[3] = forns.getInscricaoestadual();
            fila[4] = forns.getTelefone();
            fila[5] = forns.getRua();
            fila[6] = forns.getBairro();
            fila[7] = forns.getNumero();
            fila[8] = forns.getCidade();
            fila[9] = forns.getUf();
            fila[10] = forns.getPedidominimo();
            fila[11] = forns.getObservacoes();
            modelo.addRow(fila);
            Tabela.setModel(modelo);
            cnpj.setText(null);
            
        }else{
            
            ArrayList<Fornecedor> forns = new ArrayList<>();
            
            try {
                forns = (ArrayList<Fornecedor>) f.consultaRazaoSocial(razao.getText());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro");
            }
            if( forns.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não encontrado");
                return;        
            }
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Razão Social", "CNPJ", "Nome Fantasia", "Inscrição Estadual", "Telefone", "Rua", "Bairro", "Numero", "Cidade", "UF", "Pedido Minimo", "Observações"});
            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < forns.size(); i++) {
                fila[0] = forns.get(i).getRazaosocial();
                fila[1] = forns.get(i).getCnpj();
                fila[2] = forns.get(i).getNomefantasia();
                fila[3] = forns.get(i).getInscricaoestadual();
                fila[4] = forns.get(i).getTelefone();
                fila[5] = forns.get(i).getRua();
                fila[6] = forns.get(i).getBairro();
                fila[7] = forns.get(i).getNumero();
                fila[8] = forns.get(i).getCidade();
                fila[9] = forns.get(i).getUf();
                fila[10] = forns.get(i).getPedidominimo();
                fila[11] = forns.get(i).getObservacoes();
                modelo.addRow(fila);
            }
            Tabela.setModel(modelo);
            razao.setText(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        consultarTodos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selecionada = Tabela.getSelectedRow();
        if (selecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum selecionado", "Mensagem", JOptionPane.ERROR_MESSAGE, null);
        }else{
            String str = Tabela.getValueAt(selecionada, 1).toString();
            DAOFornecedor c = new DAOFornecedor();
            try {
                c.exclui(str);
                JOptionPane.showMessageDialog(null, "Excluido com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE, null);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir", "Mensagem", JOptionPane.ERROR_MESSAGE, null);
            }
        }
        consultarTodos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        InserirFornecedor c = new InserirFornecedor();
        c.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selecionada = Tabela.getSelectedRow();
        if (selecionada == -1){
            JOptionPane.showMessageDialog(null, "Nenhum selecionado", "Mensagem", JOptionPane.ERROR_MESSAGE, null);
        }else{
            Fornecedor forn = new Fornecedor(Tabela.getValueAt(selecionada, 1).toString(), Tabela.getValueAt(selecionada, 0).toString(), 
            Tabela.getValueAt(selecionada, 2).toString(), Tabela.getValueAt(selecionada, 3).toString(), Tabela.getValueAt(selecionada, 4).toString(), 
            Tabela.getValueAt(selecionada, 5).toString(), Tabela.getValueAt(selecionada, 6).toString(), Tabela.getValueAt(selecionada, 7).toString(),
            Tabela.getValueAt(selecionada, 8).toString(), Tabela.getValueAt(selecionada, 9).toString(), Tabela.getValueAt(selecionada, 10).toString(),
            Tabela.getValueAt(selecionada, 11).toString());
            AlterarFornecedor a = new AlterarFornecedor();
            a.setF(forn);
            a.carregarDados();
            a.setVisible(true);
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField razao;
    // End of variables declaration//GEN-END:variables
}
